[server]
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 10
enableWebsocketCompression = true
enableStaticServing = true

[browser]
gatherUsageStats = false
ga4_tracking = "G-LGNTBK3HJ6"

[client]
caching = true
displayEnabled = true

[runner]
fastReruns = true
enforceSerializableSessionState = false

[theme]
base = "dark"
